CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE, /* NOT IN USE FOR NOW; EMAIL REMINDERS NOT IMPLEMENTED */
  password VARCHAR(60) NOT NULL /* NOT IN USE FOR NOW; AUTHENTICATION NOT IMPLEMENTED */
);

CREATE TABLE sessions ( /* NOT IN USE FOR NOW; AUTHENTICATION NOT IMPLEMENTED */
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE tasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  userId INT NOT NULL REFERENCES users (id) ON DELETE SET NULL,
  title VARCHAR(50) NOT NULL,
  description VARCHAR(100),
  status VARCHAR(20) NOT NULL,
  dueDate VARCHAR(20) NOT NULL
);

CREATE TABLE subtasks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  taskId INT NOT NULL REFERENCES tasks (id) ON DELETE SET NULL,
  title VARCHAR(50) NOT NULL,
  description VARCHAR(100),
  status VARCHAR(20) NOT NULL
);